######################################################################
##
## Filename: game_mgr.udo
## Created on: Fri Mar 18 15:46:01 Paris, Madrid 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
